class TcpTransportAsync:
    def __init__(self, host: str, port: int = ...) -> None: ...
    async def bulk_read(
        self, numbytes: int, transport_timeout_s: float | None
    ) -> bytes: ...
    async def bulk_write(
        self, data: bytes | bytearray, transport_timeout_s: float | None
    ) -> int: ...
    async def connect(self, transport_timeout_s: float | None) -> None: ...
    async def close(self) -> None: ...
