import { readBounded } from './bounded-stream.mjs';

export class ShellSessionError extends Error {
  constructor(code) { super(code); this.code = code; }
}

// Used only with fixed programs generated by this application. Installation
// explicitly opts into 180 seconds; read-only callers retain their shorter limits.
// A timeout requires ending the owning connection, never trying another dialect.
export async function readShell(adb, command, { maximum = 32768, timeoutMs = 3000, closeMs = 2000 } = {}) {
  if (typeof command !== 'string' || !command || command.length > 16384 ||
      !Number.isSafeInteger(maximum) || maximum < 1 || maximum > 32768 ||
      !Number.isSafeInteger(timeoutMs) || timeoutMs < 1 || timeoutMs > 180000 ||
      !Number.isSafeInteger(closeMs) || closeMs < 1 || closeMs > 2000) throw new ShellSessionError('invalid_request');
  let socket;
  let expired = false;
  let timer;
  const operation = (async () => {
    socket = await adb.createSocket(`shell:${command}`);
    if (expired) {
      void Promise.resolve(socket.close()).catch(() => {});
      throw new ShellSessionError('shell_timeout');
    }
    return readBounded(socket.readable, maximum);
  })();
  try {
    return await Promise.race([operation, new Promise((_, reject) => {
      timer = setTimeout(() => {
        expired = true;
        reject(new ShellSessionError('shell_timeout'));
      }, timeoutMs);
    })]);
  } finally {
    clearTimeout(timer);
    if (socket) {
      let closeTimer;
      try {
        await Promise.race([Promise.resolve().then(() => socket.close()), new Promise((_, reject) => {
          closeTimer = setTimeout(() => reject(new ShellSessionError('shell_cleanup_failed')), closeMs);
        })]);
      } catch { throw new ShellSessionError('shell_cleanup_failed'); }
      finally { clearTimeout(closeTimer); }
    }
  }
}
