"""Constants for the ha-paneld integration."""

from datetime import timedelta

DOMAIN = "ha_paneld"

DEFAULT_PORT = 8888
DEFAULT_SCAN_INTERVAL = timedelta(seconds=30)
DEFAULT_TIMEOUT_SECONDS = 5
MAX_HEALTH_RESPONSE_BYTES = 512
MAX_STATUS_RESPONSE_BYTES = 64 * 1024
MAX_STATUS_WARNINGS = 32
MAX_STATUS_CAPABILITIES = 32
MAX_STATUS_REASON_CODES = 32
MAX_STATUS_WARNING_LENGTH = 2048
MAX_STATUS_TOKEN_LENGTH = 128
MAX_STATUS_FAULT_DETAIL_LENGTH = 40
MAX_STATUS_INTEGER = 2**63 - 1
MIN_ANDROID_INTEGER = -(2**31)
MAX_ANDROID_INTEGER = 2**31 - 1
MAX_ZIGBEE_CPU_PERCENT = 1000

HEALTH_PATH = "/api/v1/health"
STATUS_PATH = "/api/v1/status"
